[project]
name = "odoo-addons-oca-hr"
version = "17.0.20250709.0"
dependencies = [
    "odoo-addon-hr_announcement>=17.0dev,<17.1dev",
    "odoo-addon-hr_contract_bonus>=17.0dev,<17.1dev",
    "odoo-addon-hr_course>=17.0dev,<17.1dev",
    "odoo-addon-hr_department_code>=17.0dev,<17.1dev",
    "odoo-addon-hr_employee_age>=17.0dev,<17.1dev",
    "odoo-addon-hr_employee_calendar_planning>=17.0dev,<17.1dev",
    "odoo-addon-hr_employee_document>=17.0dev,<17.1dev",
    "odoo-addon-hr_employee_firstname>=17.0dev,<17.1dev",
    "odoo-addon-hr_employee_language>=17.0dev,<17.1dev",
    "odoo-addon-hr_employee_medical_examination>=17.0dev,<17.1dev",
    "odoo-addon-hr_employee_partner_external>=17.0dev,<17.1dev",
    "odoo-addon-hr_employee_ppe>=17.0dev,<17.1dev",
    "odoo-addon-hr_employee_relative>=17.0dev,<17.1dev",
    "odoo-addon-hr_employee_second_lastname>=17.0dev,<17.1dev",
    "odoo-addon-hr_employee_ssn>=17.0dev,<17.1dev",
    "odoo-addon-hr_job_category>=17.0dev,<17.1dev",
    "odoo-addon-hr_personal_equipment_request>=17.0dev,<17.1dev",
    "odoo-addon-hr_professional_category>=17.0dev,<17.1dev",
    "odoo-addon-hr_study>=17.0dev,<17.1dev",
    "odoo-addon-hr_work_entry_profile>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
